services:
  - type: web
    runtime: node
    name: share-movements-backend
    rootDir: apps/server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: "3001"

  - type: web
    runtime: static
    name: share-movements-frontend
    rootDir: apps/web
    buildCommand: npm install --workspace apps/web && npm --workspace apps/web run build
    staticPublishPath: apps/web/dist
